### ISSUE TITLE
Not able to commit to master

### ISSUE THREAD

**Issue by BMaster123** [TheAlgorithms/Python#4584]
Check that executables have shebangs.....................................Passed
Check Yaml...........................................(no files to check)Skipped
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
Fix requirements.txt.................................(no files to check)Skipped
black....................................................................Passed
isort....................................................................Passed
flake8...................................................................Passed
codespell................................................................Passed
Validate filenames.......................................................Failed
- hook id: validate-filenames
- exit code: 9009

Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

This is what shows up every time I try to commit. I have tried to change the app execution aliases as it says. I'm not sure what I'm doing wrong. How can I fix this? Sorry if this issue is a no-brainer but I'm new to contributing.

**Comment by Sin-Sumit** [comment]
Hi, Can you please tell me that whether I understand your problem or not?
I think you are not able to make a commit in the master branch in your account or this account. Or any other issue.

**Comment by kkanekii** [comment]
do you have python installed on your computer?

**Comment by Sin-Sumit** [comment]
yes

**Comment by kkanekii** [comment]
@Sin-Sumit are u having a problem too

**Comment by Sin-Sumit** [comment]
No

**Comment by kkanekii** [comment]
Please stop affirmating and extending the thread for no reason then.

**Comment by BMaster123** [comment]
Sorry for the late response. Yes, I have python installed on my computer. I looked up how to fix this online and it said I needed to turn off one of the python app execution aliases like the error says but this solution did not work for me.

**Comment by BMaster123** [comment]
@Sin-Sumit To answer your question I forked this repository and tried to push my additions to the fork. When I pushed it it ran the tests in the issue above and the "Validate filenames" test failed.

**Comment by kkanekii** [comment]
Oh, make sure you don't have any spaces in your file name, make sure your file doesn't start with a capital letter, that should fix it :))

**Comment by Master7130** [comment]
My file's name is "baconian_cipher.py" with no spaces :(

**Comment by kkanekii** [comment]
I don't know then, try changing your file name, make it somin really simple like my file.py so we know if its because of your file or it's a computer problem, if the problem persists, then I don't know what to do

**Comment by Master7130** [comment]
Yeah the problem is still there. Thanks for trying to help tho.

**Comment by kkanekii** [comment]
The computer is related to this problem, try re installing python

**Comment by Master7130** [comment]
I tried that as well but it didn't work

**Comment by kkanekii** [comment]
what version of Python are you using

**Comment by kkanekii** [comment]
python -v or python -version should tell the version

**Comment by Master7130** [comment]
3.7.5

**Comment by kkanekii** [comment]
if none of them work, try stackoverflow

**Comment by L3str4nge** [comment]
You cannot push to the master branch of this repository because you don't have permissions for doing that. If your problem is global (not related to this repo) please use stackoverflow/google for solve.

**Comment by kkanekii** [comment]
@L3str4nge , He has forked this repo and wants to push to that, so he will have permissions, although i agree stackoverflow should be used.

**Comment by Rhushal777** [comment]
Yes

**Comment by kkanekii** [comment]
@Rhushal777 what?
