### ISSUE TITLE
Project euler problem 104 broken

### ISSUE THREAD

**Issue by CaedenPH** [TheAlgorithms/Python#7069]
### Feature description

Disable project euler problem 104

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by AnishJoshi13** [comment]
I would like to work on this issue. Please assign it to me

**Comment by cclauss** [comment]
There is no assigning in this repository.  If you can fix it then please create a pull request.  If you and someone else both create pull requests then we can review them both and select the best one.  Waiting to be assigned it a waste of time.

**Comment by dhruvmanila** [comment]
@cclauss should the bot/workflow add a comment similar to what you just mentioned every time an issue is opened? I see people keep on asking to be assigned.

**Comment by dhruvmanila** [comment]
Also, @CaedenPH this seems like a bug, please use the bug template.

**Comment by CaedenPH** [comment]
@dhruvmanila 
The problem with the bug report template is that it wants python version and dependencies version for a problem that is just clearly broken. The checks have failed on it and therefore it has the `.FIXME` extension. This is technically a feature request because the bug has been fixed and now it's just a feature to either rewrite it or fix it

**Comment by cclauss** [comment]
> should the bot/workflow add a comment 

Yes please!  People waiting to be assigned drives me nuts!

**Comment by CaedenPH** [comment]
> > should the bot/workflow add a comment 
> 
> 
> 
> Yes please!  People waiting to be assigned drives me nuts!

I thought most of the people commenting that are hacktoberfest bots?

**Comment by cclauss** [comment]
I am all for having our bot confuse their bot ;-)

**Comment by dhruvmanila** [comment]
> The problem with the bug report template is that it wants python version and dependencies version for a problem that is just clearly broken.

If you would look closely, you'll realize that the Python version does matter when reproducing the bug as this is the cause of the error: https://docs.python.org/3/whatsnew/3.10.html#notable-security-feature-in-3-10-7 which was introduced in Python 3.10.7

> The checks have failed on it and therefore it has the `.FIXME` extension. This is technically a feature request because the bug has been fixed and now it's just a feature to either rewrite it or fix it

By adding a random extension, the problem is just postponed and not fixed. So, this is not a feature request, but a bug which needs to be fixed as per the latest fixes in the language itself.

**Comment by cclauss** [comment]
As long as there is an issue opened to fix the disabling, I see no problem as long as there is significant value in disabling.

I asked @CaedenPH to disable one algorithm in this way and open a new issue to get it fixed.  This one algorithm was blocking a PR that @CaedenPH was working on that had 100+ files modified.  These kind of pull requests quickly raise conflicts on busy repos.
