### ISSUE TITLE
[PYTEST WARNING] Machine learning forecasting

### ISSUE THREAD

**Issue by CaedenPH** [TheAlgorithms/Python#7305]
### Feature description

@nandiya Please could you resolve this warning
```
machine_learning/forecasting/run.py::machine_learning.forecasting.run.sarimax_predictor
  /opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/statsmodels/tsa/statespace/sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
    warn('Too few observations to estimate starting parameters%s.'

machine_learning/forecasting/run.py::machine_learning.forecasting.run.sarimax_predictor
  /opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/statsmodels/tsa/statespace/sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for seasonal ARMA. All parameters except for variances will be set to zeros.
    warn('Too few observations to estimate starting parameters%s.'

machine_learning/forecasting/run.py::machine_learning.forecasting.run.sarimax_predictor
  /opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3715: RuntimeWarning: Degrees of freedom <= 0 for slice
    return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

machine_learning/forecasting/run.py::machine_learning.forecasting.run.sarimax_predictor
  /opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/numpy/core/_methods.py:223: RuntimeWarning: invalid value encountered in divide
    arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',

machine_learning/forecasting/run.py::machine_learning.forecasting.run.sarimax_predictor
  /opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/numpy/core/_methods.py:257: RuntimeWarning: invalid value encountered in double_scalars
    ret = ret.dtype.type(ret / rcount)
```

origin: #7211

**Comment by tianyizheng02** [comment]
@cclauss I think this issue should be reopened since the pytest warnings were never resolved

**Comment by cclauss** [comment]
My sense is that these warnings were solved but new ones have come up.

**Comment by tianyizheng02** [comment]
In the pytest logs from the most recent build [here](https://github.com/TheAlgorithms/Python/actions/runs/3821763434/jobs/6501234607#step:6:678), it appears that the 5 warnings cited above are still present
